export type Match = {
  id: string;
  roundId: string;
  roundLabel: string;
  kickoffUtc: string;
  stadium: string | null;
  venueCity: string | null;
  status: string;
  homeTeamId: string;
  homeName: string;
  homeLogoUrl: string | null;
  homePrimaryColor?: string;
  homeSecondaryColor?: string;
  awayTeamId: string;
  awayName: string;
  awayLogoUrl: string | null;
  awayPrimaryColor?: string;
  awaySecondaryColor?: string;
  homeGoals: number | null;
  awayGoals: number | null;
  homeStanding: number | null;
  awayStanding: number | null;
  homeForm: string | null;
  awayForm: string | null;
  oddsHome: number | null;
  oddsDraw: number | null;
  oddsAway: number | null;
};
